### ISSUE TITLE
Como puedo ayudar?

### ISSUE THREAD

**Issue by pachadotdev** [FranciscoDA/redatam4r#1]
Me interesa esto

**Comment by FranciscoDA** [comment]
Hola, a continuación algunas tareas pendientes:
 * No todo el contenido del archivo diccionario está descifrado, quedan algunos campos desconocidos, como verás en los siguientes archivos:
   * https://github.com/FranciscoDA/redatam4r/blob/master/src/dic/variable_descriptor.h 
   * https://github.com/FranciscoDA/redatam4r/blob/master/src/dic/entity_descriptor.h
   * https://github.com/FranciscoDA/redatam4r/blob/master/src/dic/dictionary_descriptor.h
 * Las versiones nuevas de Redatam guardan el diccionario en formato XML (con extensión .dicx). Sería muy útil agregar soporte para este formato

Si no tenés una instalación de Redatam+SP para hacer el reversing, podés descargarla desde acá: https://www.cepal.org/es/temas/redatam/download-redatam (sólo Windows)

Si no tenés una base de datos Redatam para probar el proyecto, el instalador de Redatam+SP contiene una base de datos de prueba (Nueva Miranda) que debería funcionar con este paquete. La ruta por defecto al diccionario de Nueva Miranda es `Archivos de Programa\Redatam\NMIR\BaseR\NmirEsp.dic`

Si tenés una base de datos que no se puede abrir con este paquete, podrías:
 * Hacer los cambios que consideres necesarios para hacerlo funcionar. Después los vemos en un pull request ;)
 * Hacérmela llegar, cuando tenga tiempo le puedo echar un vistazo

Saludos!
