### ISSUE TITLE
estado del proyecto

### ISSUE THREAD

**Issue by pachadotdev** [FranciscoDA/redatam4r#4]
hola

cual es el estado del proyecto?

**Comment by FranciscoDA** [comment]
Hola.

El proyecto no recibe actualizaciones desde hace algunos años.

Entiendo que el formato de archivos de redatam sufrio modificaciones en este lapso, por lo que es probable que el proyecto no funcione con bases de datos de los censos que se realizaron en los ultimos años.

Logicamente se aceptan y aprecian aportes que puedan contribuir con esto o con otros issues

**Comment by pachadotdev** [comment]
gracias! ahora salio redatam x, que no logro instalar en mac

**Comment by FranciscoDA** [comment]
Estuve indagando un poco y encontre la siguiente nota en la web de la cepal: https://www.cepal.org/es/enfoques/manejo-basico-redatam-usando-r-la-estimacion-estadisticas-desagregadas

Hacen referencia a un paper que no logro encontrar, el cual describe un paquete de R para leer bases de datos redatamx que no está en CRAN

**Comment by pachadotdev** [comment]
> Estuve indagando un poco y encontre la siguiente nota en la web de la cepal: https://www.cepal.org/es/enfoques/manejo-basico-redatam-usando-r-la-estimacion-estadisticas-desagregadas
> 
> Hacen referencia a un paper que no logro encontrar, el cual describe un paquete de R para leer bases de datos redatamx que no está en CRAN

si, ese mismo, no logro encontrarlo, ellos me enviaron un zip para windows

**Comment by andresnecochea** [comment]
Hola.
Sé que esto es antiguo, pero quería comentar que el paquete R para redatam, que todavía no está en CRAN, se puede bajar en las descargas de Redatam X:
https://redatam.org/es/aplicaciones

Ojalá tengamos, algún día, una forma oficial de leer bases de datos censales en R.

**Comment by pachadotdev** [comment]
> Hola. Sé que esto es antiguo, pero quería comentar que el paquete R para redatam, que todavía no está en CRAN, se puede bajar en las descargas de Redatam X: https://redatam.org/es/aplicaciones
> 
> Ojalá tengamos, algún día, una forma oficial de leer bases de datos censales en R.

lo que hice en https://github.com/pachadotdev/censo2017 fue usar un programa para Windows que hizo Pablo De Grande

**Comment by pachadotdev** [comment]
hola @FranciscoDA 
en https://github.com/pachadotdev/redatam-converter/tree/main/rpkg hice algo que funciona con redatam (dic y dicx) por ahora
